version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - pwd
      - npm install
  build:
    commands:
      - echo Entered the build phase...
      - pwd
      - npm run ng build --prod
    finally:
      - echo This always runs even if the install command fails
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`

artifacts:
  files:
    - dist/my-profile/*
  discard-paths: yes
