version: 0.2
phases:
  install:
    commands:      
      - apt-get update -y
      - apt-get install -y libssl1.0-dev nodejs-dev node-gyp   
      - apt-get install -y npm    
  pre_build:
    commands:
      - pwd
      - npm install
  build:
    commands:
      - echo Entered the build phase...
      - pwd
      - ng build --prod
    finally:
      - echo This always runs even if the install command fails
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`

artifacts:
  files:
    - dist/my-profile/*
  discard-paths: yes
